name: app
version: 0.1.0.0
dependencies:
  - base
  - megaparsec
  - containers
  - sqlite-simple
  - directory
  - Glob
  - text
  - clock
  - formatting
  - errors
  - raw-strings-qq
default-extensions:
  - OverloadedStrings
  - QuasiQuotes
  - LambdaCase
  - MultiWayIf
  - TemplateHaskell
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - NoMonomorphismRestriction
  - BangPatterns
  - ScopedTypeVariables
  - TupleSections
  - DeriveFunctor
  - DeriveTraversable
  - DeriveFoldable
  - DeriveGeneric
executables:
  app:
    source-dirs: src
    main: Main.hs
